site_name: Modulos
nav:
    - Home: index.md
    - Modulos:
        - Getting Started: modulos/index.md
        - Pipeline pattern: modulos/pipeline/index.md
    - Modulos.Testing: modulos.testing/index.md
    - Modulos.Testing.Db: modulos.testing.db/index.md
    - Modulos.Messaging:
        - Getting Started: modulos.messaging/index.md
theme: readthedocs